import * as _angular_core from '@angular/core';
import { AfterViewInit, OnDestroy, ElementRef } from '@angular/core';

declare class QScrollAreaComponent implements AfterViewInit, OnDestroy {
    viewportRef: ElementRef<HTMLElement>;
    scrollbarXRef: ElementRef<HTMLElement>;
    scrollbarYRef: ElementRef<HTMLElement>;
    thumbXRef: ElementRef<HTMLElement>;
    thumbYRef: ElementRef<HTMLElement>;
    cornerRef: ElementRef<HTMLElement>;
    _hostClass: string;
    get _dataQtBinding(): string;
    _onMouseEnter: () => void;
    _onMouseleave: () => void;
    handlePointermove: (event: PointerEvent) => void;
    handlePointerUp: (event: PointerEvent) => void;
    visibilityMode: _angular_core.InputSignal<"auto" | "scroll" | "always" | "hover">;
    displayMode: _angular_core.InputSignal<"overlay" | "inline">;
    hideDelay: _angular_core.InputSignalWithTransform<number, unknown>;
    enableScrollShadow: _angular_core.InputSignalWithTransform<boolean, unknown>;
    dataQt: _angular_core.InputSignal<string>;
    _showScrollbarX: _angular_core.Signal<boolean>;
    _showScrollbarY: _angular_core.Signal<boolean>;
    _shouldReserveSpaceX: _angular_core.Signal<boolean>;
    _shouldReserveSpaceY: _angular_core.Signal<boolean>;
    _showCorner: _angular_core.Signal<boolean>;
    _viewportPaddingRight: _angular_core.Signal<number | null>;
    _viewportPaddingBottom: _angular_core.Signal<number | null>;
    _thumbPositionX: number;
    _thumbPositionY: number;
    _ariaValueNowX: number;
    _ariaValueNowY: number;
    _thumbSizeX: number;
    _thumbSizeY: number;
    _scrollbarXSize: number;
    _scrollbarYSize: number;
    _cornerWidth: number;
    _cornerHeight: number;
    _viewportId: string;
    private _hasOverflowX;
    private _hasOverflowY;
    private _scrollState;
    private _hideTimeout;
    private _dragAxis;
    private _dragStartPos;
    private _initialScrollPos;
    private _pointerOffset;
    private _originalScrollBehavior;
    private _resizeRAF;
    private _isDragging;
    private _isDestroyed;
    private _scrollListenerCleanup;
    private _debouncedScrollEndCleanup;
    private _debouncedResizeCleanup;
    private _debouncedScrollEnd;
    private _debouncedResize;
    private readonly _resizeObserverService;
    private readonly _cdr;
    private readonly _zone;
    private readonly _destroy$;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    handleWheel(event: WheelEvent): void;
    handlePointerDown(event: PointerEvent, axis: 'x' | 'y'): void;
    private _handleTrackClick;
    private _handleThumbDrag;
    private _handleInteraction;
    private _initializeScrollListener;
    private _initializeResizeObserver;
    private _startHideTimeout;
    private _updateScrollbar;
    private _updateThumbPositions;
    private _updateCornerSizes;
    private _createDebounceCallback;
    private _handleMouseenter;
    private _handleMouseleave;
    private _handlePointermove;
    private _handlePointerup;
    private _getShowScrollbarX;
    private _getShowScrollbarY;
    private _getShouldReserveSpaceX;
    private _getShouldReserveSpaceY;
    private _getViewportPaddingRight;
    private _getViewportPaddingBottom;
    private _initializeScrollbarSizes;
    private _initializeDebouncedCallbacks;
    private _isScrollingWithinScrollbarBounds;
    private _linearScale;
    private _clamp;
    private _toInt;
    private _getThumbRatio;
    private _getThumbSize;
    private _getThumbOffsetFromScroll;
    private _getScrollPositionFromPointer;
    static ɵfac: _angular_core.ɵɵFactoryDeclaration<QScrollAreaComponent, never>;
    static ɵcmp: _angular_core.ɵɵComponentDeclaration<QScrollAreaComponent, "q-scroll-area, [q-scroll-area], [qScrollArea]", never, { "visibilityMode": { "alias": "visibilityMode"; "required": false; "isSignal": true; }; "displayMode": { "alias": "displayMode"; "required": false; "isSignal": true; }; "hideDelay": { "alias": "hideDelay"; "required": false; "isSignal": true; }; "enableScrollShadow": { "alias": "enableScrollShadow"; "required": false; "isSignal": true; }; "dataQt": { "alias": "dataQt"; "required": false; "isSignal": true; }; }, {}, never, ["*"], true, never>;
}

declare const QScrollAreaDisplayModeValues: readonly ["overlay", "inline"];
type QScrollAreaDisplayMode = (typeof QScrollAreaDisplayModeValues)[number];

declare const QScrollAreaVisibilityModeValues: readonly ["auto", "always", "scroll", "hover"];
type QScrollAreaVisibilityMode = (typeof QScrollAreaVisibilityModeValues)[number];

export { QScrollAreaComponent, QScrollAreaDisplayModeValues, QScrollAreaVisibilityModeValues };
export type { QScrollAreaDisplayMode, QScrollAreaVisibilityMode };
